"""dodanie_pol_nadawcy_odbiorcy_do_parcel

Revision ID: c226b2f3426a
Revises: af364709e40b
Create Date: 2026-04-18 09:58:34.363309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c226b2f3426a'
down_revision: Union[str, Sequence[str], None] = 'af364709e40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('sender_custom_name', sa.String(length=200), nullable=False))
    op.add_column('parcels', sa.Column('sender_phone', sa.String(length=20), nullable=False))
    op.add_column('parcels', sa.Column('recipient_custom_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'recipient_custom_name')
    op.drop_column('parcels', 'sender_phone')
    op.drop_column('parcels', 'sender_custom_name')
    # ### end Alembic commands ###
